package com.canolabs.rallytransbetxi.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF735C00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFE085)
val md_theme_light_onPrimaryContainer = Color(0xFF231B00)
val md_theme_light_secondary = Color(0xFF735C00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFE086)
val md_theme_light_onSecondaryContainer = Color(0xFF231B00)
val md_theme_light_tertiary = Color(0xFF46664B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC8ECCA)
val md_theme_light_onTertiaryContainer = Color(0xFF02210C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1E1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1E1B16)
val md_theme_light_surfaceVariant = Color(0xFFEBE2CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4C4639)
val md_theme_light_outline = Color(0xFF7D7667)
val md_theme_light_inverseOnSurface = Color(0xFFF7F0E7)
val md_theme_light_inverseSurface = Color(0xFF33302A)
val md_theme_light_inversePrimary = Color(0xFFE8C349)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF735C00)
val md_theme_light_outlineVariant = Color(0xFFCEC6B4)
val md_theme_light_scrim = Color(0xFF000000)
val ruralColor = Color(0xFF315742)

val md_theme_dark_primary = Color(0xFFE8C349)
val md_theme_dark_onPrimary = Color(0xFF3C2F00)
val md_theme_dark_primaryContainer = Color(0xFF574500)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFE085)
val md_theme_dark_secondary = Color(0xFFE8C349)
val md_theme_dark_onSecondary = Color(0xFF3C2F00)
val md_theme_dark_secondaryContainer = Color(0xFF574500)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFE086)
val md_theme_dark_tertiary = Color(0xFFACCFAF)
val md_theme_dark_onTertiary = Color(0xFF183720)
val md_theme_dark_tertiaryContainer = Color(0xFF2F4E35)
val md_theme_dark_onTertiaryContainer = Color(0xFFC8ECCA)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1E1B16)
val md_theme_dark_onBackground = Color(0xFFE8E2D9)
val md_theme_dark_surface = Color(0xFF1E1B16)
val md_theme_dark_onSurface = Color(0xFFE8E2D9)
val md_theme_dark_surfaceVariant = Color(0xFF4C4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFCEC6B4)
val md_theme_dark_outline = Color(0xFF979080)
val md_theme_dark_inverseOnSurface = Color(0xFF1E1B16)
val md_theme_dark_inverseSurface = Color(0xFFE8E2D9)
val md_theme_dark_inversePrimary = Color(0xFF735C00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFE8C349)
val md_theme_dark_outlineVariant = Color(0xFF4C4639)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFEDCF75)
